### ISSUE TITLE
Simplified login check handling

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-angular#6]
The code to check if the user is logged in is very complicated [1]. It'd be much simpler if `auth.update()` returned a promise, and was used in a route resolve function [2].

An alternative more general implementation to the route resolve functions would be to add an "auth required" property to each route that requires it, and handle the general case from the authentication module using route state transitions.

[1] https://github.com/yunity/yunity-angular/blob/master/client/app/components/home/home.hook.js
[2] https://github.com/angular-ui/ui-router/wiki#resolve

**Comment by Sneezoo** [comment]
Yeah, you're right @nicksellen. It was more like a quick 'n' dirty solution.
In this step I would also like to split the parts of fetching and keeping data in separate services, making the process of fetching replaceable with any logic. I also may still broadcast events in case some parts of the application will need it, but I will also return Promises to clean up the messy transition hooks code.
I'd also like to add an property for states that you should not see if you're already logged in, like sign up and login.

**Comment by Sneezoo** [comment]
A thing about _resolve_: I would like to make a transition to login if the authentication check goes wrong.
I could listen to _$stateChangeSuccess_ or something but that seems to be [deprecated](https://ui-router.github.io/docs/latest/modules/ng1_state_events.html#_statechangestart)
My idea is to do something like what the documentation says in this [example](https://ui-router.github.io/docs/latest/classes/transition.transitionservice.html#onstart) or with onBefore hook like I did.
Then I can inject the `/api/auth/status` data into the home controller by calling a simple ``Authentication.credentials()`` which returns the kept data I received executing the transition hook.

**Comment by nicksellen** [comment]
Yup sounds like transition logic stuff would best solve that. On the other
hand sometimes a login/signup modal is nice and you dont need to change the
url for that.

The main problem before wasnt actually the use of transitions but the
broadcast bit instead of promises. It was very tricky to test.

**Comment by Sneezoo** [comment]
I want to include @D0nPiano's work in [yunity/yunity-MVP-proposal-AngularMaterial
](https://github.com/yunity/yunity-MVP-proposal-AngularMaterial). A login page fits best for that.

Yeah I agree, I will fix that.
